spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

# Swagger UI по /swagger-ui.html
swagger-ui:
  path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: notes-calendar
