server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: notes
    password: notes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
