name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build + Tests + Checks
        run: ./gradlew --no-daemon clean check jacocoTestReport bootJar

      - name: Upload reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-java${{ matrix.java }}
          path: |
            build/reports/tests/test
            build/reports/jacoco/test
            build/reports/checkstyle
            build/reports/spotless

      - name: Upload JAR (only on 17)
        if: success() && matrix.java == '17'
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
