name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            gradle/wrapper/gradle-wrapper.properties

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build + Tests + Checks
        run: ./gradlew --no-daemon clean check jacocoTestReport

      - name: Upload reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/reports/tests/test
            build/reports/jacoco/test
            build/reports/checkstyle
            build/reports/spotless

      - name: Upload JAR (on success)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
